CREATE DATABASE pawsome_vibes_db;
DROP DATABASE IF EXISTS pawsome_vibes_db;

\c pawsome_vibes_db;



CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE affirmations (
  id SERIAL PRIMARY KEY,
  text TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorites (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  affirmation_id INTEGER REFERENCES affirmations(id) ON DELETE CASCADE
);